import { ChevronDown } from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "./ui/accordion";

export function Header() {
  return (
    <div className="mb-12">
      <div className="text-center mb-8">
        <h1 className="text-4xl mb-3 text-foreground">
          Meme Explanation Evaluation Study
        </h1>
        <p className="text-lg text-muted-foreground">
          AI Model Interpretation Research
        </p>
      </div>

      <Accordion
        type="multiple"
        className="max-w-4xl mx-auto space-y-3"
      >
        <AccordionItem
          value="about"
          className="border border-border bg-card/50 rounded-lg px-6 backdrop-blur-sm"
        >
          <AccordionTrigger className="hover:no-underline py-4">
            <span className="text-base">About the Study</span>
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground pb-4">
            <p className="mb-3">
            This survey is part of the thesis "Methods for Evaluating the Quality of Explainable Artificial Intelligence Models"
            </p>
            <p>
             You will see a meme and several explanations generated by AI about how the model made its decision. 
             Your task is simple: evaluate each explanation according to the 6 characteristics provided.
             <br />
             <br />
             There are no right or wrong answers. We are interested in your opinion.
             <br />
             <br />
             Thank you for your time and participation.
            </p>
           
          </AccordionContent>
        </AccordionItem>

        <AccordionItem
          value="model"
          className="border border-border bg-card/50 rounded-lg px-6 backdrop-blur-sm"
        >
          <AccordionTrigger className="hover:no-underline py-4">
            <span className="text-base">How It Works</span>
          </AccordionTrigger>
          <AccordionContent className="text-muted-foreground pb-4">
            <p className="mb-3"><b>We used two machine learning models to classify memes:</b></p>
            <p>
                [1] a text-only model that analyzes the text and description of the meme,
            <br />
                [2] and a multimodal model that analyzes both the image and text.
            </p>
            <p>
            <br />
            (Depending on your group, you will see explanations for one of these models)
            <br />
            <br />
            For each meme, we applied three different methods of explainable artificial intelligence to show why the model classified the meme in this particular way.
            </p>
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}
